apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swagger-nodejs
  name: swagger-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-nodejs
  template:
    metadata:
      labels:
        app: swagger-nodejs
    spec:
      containers:
      - image:  nodez.azurecr.io/swagger-nodejs:latest
        name: swagger-nodejs       
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger-nodejs
  name: swagger-nodejs
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: swagger-nodejs
  type: LoadBalancer
